-- Product Storage bucket migration
-- Logical scope: product_storage_policy
-- Generated by Supabase CLI as 20260701130506_product_storage_policy.sql.
--
-- Purpose:
-- - Ensure the product-files Storage bucket exists.
-- - Keep product-files private.
-- - Set conservative upload limits when the hosted Storage schema supports them.
--
-- Important production note:
-- - The original version attempted to create policies on storage.objects.
-- - Hosted Supabase SQL execution can fail with:
--   ERROR: 42501: must be owner of relation objects
-- - Because storage.objects is owned by the Supabase Storage service role, this
--   migration is intentionally bucket-only.
-- - storage.objects policies must be configured through Supabase Storage policy
--   tooling or a privileged migration path that owns storage.objects.
--
-- Safety:
-- - No production data backfill.
-- - No product submit/upload UI connection.
-- - No service-role fallback.
-- - No delete policies.
-- - No public bucket.
-- - No public bucket listing policy.
-- - No public document/certificate PDF access.
-- - No public price, Buyer PII, or Supplier-Buyer direct contact exposure.
-- - Depends on product registration core and child-table RLS migrations.

begin;

insert into storage.buckets (id, name, public)
values ('product-files', 'product-files', false)
on conflict (id) do update
set public = false;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'storage'
      and table_name = 'buckets'
      and column_name = 'file_size_limit'
  ) then
    execute $sql$
      update storage.buckets
      set file_size_limit = 26214400
      where id = 'product-files'
    $sql$;
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'storage'
      and table_name = 'buckets'
      and column_name = 'allowed_mime_types'
  ) then
    execute $sql$
      update storage.buckets
      set allowed_mime_types = array[
        'image/jpeg',
        'image/png',
        'image/webp',
        'application/pdf'
      ]::text[]
      where id = 'product-files'
    $sql$;
  end if;
end $$;

-- Deferred storage.objects policy set:
-- - product_files_supplier_insert
-- - product_files_supplier_select
-- - product_files_supplier_update
-- - product_files_admin_select
-- - product_files_admin_insert
-- - product_files_admin_update
-- - product_files_public_image_select
--
-- These policies are documented in:
-- docs/05-data/17-product-storage-policy-owner-error-resolution.md
--
-- They are deliberately not created here because the SQL execution role must own
-- storage.objects. Reintroducing CREATE POLICY ON storage.objects in this file
-- can repeat the production error: "must be owner of relation objects".

-- Validation after apply:
-- 1. Confirm bucket exists and remains private:
--    select id, name, public, file_size_limit, allowed_mime_types
--    from storage.buckets
--    where id = 'product-files';
-- 2. Confirm this migration did not create storage.objects policies:
--    select policyname, cmd, roles
--    from pg_policies
--    where schemaname = 'storage'
--      and tablename = 'objects'
--      and policyname like 'product_files_%'
--    order by policyname;
-- 3. Keep product upload UI disabled until storage.objects policies are created
--    and runtime upload/read tests pass.
--
-- Rollback preference:
-- - Disable upload UI first.
-- - Keep product-files private.
-- - Do not drop the bucket or hard-delete objects without explicit approval.

commit;
