-- Product Storage policy migration
-- Logical scope: product_storage_policy
-- Generated by Supabase CLI as 20260701130506_product_storage_policy.sql.
--
-- Purpose:
-- - Ensure the product-files Storage bucket is private.
-- - Add narrowly scoped storage.objects policies for product file upload/read.
-- - Allow public reads only for approved/published public product images.
--
-- Safety:
-- - No production data backfill.
-- - No product submit/upload UI connection.
-- - No service-role fallback.
-- - No delete policies.
-- - No public bucket listing policy.
-- - No public document/certificate PDF access.
-- - No public price, Buyer PII, or Supplier-Buyer direct contact exposure.
-- - Depends on product registration core and child-table RLS migrations.

begin;

insert into storage.buckets (id, name, public)
values ('product-files', 'product-files', false)
on conflict (id) do update
set public = false;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'storage'
      and table_name = 'buckets'
      and column_name = 'file_size_limit'
  ) then
    execute $sql$
      update storage.buckets
      set file_size_limit = 26214400
      where id = 'product-files'
    $sql$;
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'storage'
      and table_name = 'buckets'
      and column_name = 'allowed_mime_types'
  ) then
    execute $sql$
      update storage.buckets
      set allowed_mime_types = array[
        'image/jpeg',
        'image/png',
        'image/webp',
        'application/pdf'
      ]::text[]
      where id = 'product-files'
    $sql$;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'product_files_supplier_insert'
  ) then
    execute $policy$
      create policy product_files_supplier_insert
      on storage.objects
      for insert
      to authenticated
      with check (
        bucket_id = 'product-files'
        and owner_id = (select auth.uid()::text)
        and (storage.foldername(name))[1] = 'products'
        and (storage.foldername(name))[2] is not null
        and (storage.foldername(name))[3] is not null
        and (storage.foldername(name))[4] in (
          'images',
          'catalogs',
          'technical-sheets',
          'certificates',
          'manuals'
        )
        and exists (
          select 1
          from public.products
          where products.id::text = (storage.foldername(name))[3]
            and products.supplier_id = public.current_supplier_id()
            and products.supplier_id::text = (storage.foldername(name))[2]
            and products.deleted_at is null
            and products.approval_status in ('draft', 'submitted', 'reviewing', 'rejected')
            and products.publish_status <> 'published'
        )
      )
    $policy$;
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'product_files_supplier_select'
  ) then
    execute $policy$
      create policy product_files_supplier_select
      on storage.objects
      for select
      to authenticated
      using (
        bucket_id = 'product-files'
        and exists (
          select 1
          from public.files
          join public.products
            on products.id::text = (storage.foldername(storage.objects.name))[3]
          where files.bucket = storage.objects.bucket_id
            and files.path = storage.objects.name
            and files.owner_profile_id = (select auth.uid())
            and files.is_active = true
            and files.deleted_at is null
            and products.supplier_id = public.current_supplier_id()
            and products.supplier_id::text = (storage.foldername(storage.objects.name))[2]
            and products.deleted_at is null
        )
      )
    $policy$;
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'product_files_supplier_update'
  ) then
    execute $policy$
      create policy product_files_supplier_update
      on storage.objects
      for update
      to authenticated
      using (
        bucket_id = 'product-files'
        and owner_id = (select auth.uid()::text)
        and exists (
          select 1
          from public.files
          join public.products
            on products.id::text = (storage.foldername(storage.objects.name))[3]
          where files.bucket = storage.objects.bucket_id
            and files.path = storage.objects.name
            and files.owner_profile_id = (select auth.uid())
            and files.is_active = true
            and files.deleted_at is null
            and products.supplier_id = public.current_supplier_id()
            and products.supplier_id::text = (storage.foldername(storage.objects.name))[2]
            and products.deleted_at is null
            and products.approval_status in ('draft', 'submitted', 'reviewing', 'rejected')
            and products.publish_status <> 'published'
        )
      )
      with check (
        bucket_id = 'product-files'
        and owner_id = (select auth.uid()::text)
        and (storage.foldername(name))[1] = 'products'
        and (storage.foldername(name))[4] in (
          'images',
          'catalogs',
          'technical-sheets',
          'certificates',
          'manuals'
        )
        and exists (
          select 1
          from public.files
          join public.products
            on products.id::text = (storage.foldername(storage.objects.name))[3]
          where files.bucket = storage.objects.bucket_id
            and files.path = storage.objects.name
            and files.owner_profile_id = (select auth.uid())
            and files.is_active = true
            and files.deleted_at is null
            and products.supplier_id = public.current_supplier_id()
            and products.supplier_id::text = (storage.foldername(storage.objects.name))[2]
            and products.deleted_at is null
            and products.approval_status in ('draft', 'submitted', 'reviewing', 'rejected')
            and products.publish_status <> 'published'
        )
      )
    $policy$;
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'product_files_admin_select'
  ) then
    execute $policy$
      create policy product_files_admin_select
      on storage.objects
      for select
      to authenticated
      using (
        bucket_id = 'product-files'
        and public.is_admin()
      )
    $policy$;
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'product_files_admin_insert'
  ) then
    execute $policy$
      create policy product_files_admin_insert
      on storage.objects
      for insert
      to authenticated
      with check (
        bucket_id = 'product-files'
        and public.is_admin()
      )
    $policy$;
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'product_files_admin_update'
  ) then
    execute $policy$
      create policy product_files_admin_update
      on storage.objects
      for update
      to authenticated
      using (
        bucket_id = 'product-files'
        and public.is_admin()
      )
      with check (
        bucket_id = 'product-files'
        and public.is_admin()
      )
    $policy$;
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'product_files_public_image_select'
  ) then
    execute $policy$
      create policy product_files_public_image_select
      on storage.objects
      for select
      to anon, authenticated
      using (
        bucket_id = 'product-files'
        and storage.allow_any_operation(array[
          'object.get_authenticated_info',
          'object.get_authenticated'
        ])
        and exists (
          select 1
          from public.files
          join public.product_images
            on product_images.file_id = files.id
          join public.products
            on products.id = product_images.product_id
          where files.bucket = storage.objects.bucket_id
            and files.path = storage.objects.name
            and files.visibility = 'public'
            and files.is_active = true
            and files.deleted_at is null
            and product_images.approval_status = 'approved'
            and product_images.visibility = 'public'
            and product_images.deleted_at is null
            and products.approval_status = 'approved'
            and products.publish_status = 'published'
            and products.is_active = true
            and products.deleted_at is null
        )
      )
    $policy$;
  end if;
end $$;

comment on policy product_files_supplier_insert on storage.objects is
  'B2BB2G: Supplier can upload product-files objects only under their own product path.';

comment on policy product_files_supplier_select on storage.objects is
  'B2BB2G: Supplier can read objects linked to active file metadata for their own products.';

comment on policy product_files_supplier_update on storage.objects is
  'B2BB2G: Supplier can update own draft-stage product file objects; no delete policy is created.';

comment on policy product_files_admin_select on storage.objects is
  'B2BB2G: Admin can review product-files objects.';

comment on policy product_files_admin_insert on storage.objects is
  'B2BB2G: Admin can create product-files objects for operational review workflows.';

comment on policy product_files_admin_update on storage.objects is
  'B2BB2G: Admin can update product-files objects for operational review workflows.';

comment on policy product_files_public_image_select on storage.objects is
  'B2BB2G: Public can read only approved product image objects for approved and published products; no public listing or document access.';

-- Validation after apply:
-- 1. select id, name, public, file_size_limit, allowed_mime_types from storage.buckets where id = 'product-files';
-- 2. select policyname, cmd, roles from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname like 'product_files_%' order by policyname;
-- 3. confirm no product_files_% DELETE policy exists.
-- 4. confirm public object access is limited to approved image reads and does not allow bucket listing.
--
-- Rollback preference:
-- - Disable upload UI first.
-- - Repair overly broad/narrow policies with a follow-up migration.
-- - Keep product-files private.
-- - Do not drop the bucket or hard-delete objects without explicit approval.

commit;
