-- Product registration child table RLS migration
-- Logical scope: 017_product_registration_child_table_rls.sql
-- Generated by Supabase CLI as 20260701122421_product_registration_child_table_rls.sql.
--
-- Purpose:
-- - Add narrowly scoped RLS policies for product registration child tables.
-- - Keep product child tables usable only through approved public projections,
--   Supplier owner draft/submission management, or Admin review.
--
-- Safety:
-- - No production data mutation.
-- - No broad authenticated-only policies.
-- - No DELETE policies.
-- - No new SECURITY DEFINER helper functions.
-- - No public price, Buyer PII, or Supplier-Buyer direct contact exposure.
-- - Storage bucket policies are not changed in this migration.

begin;

alter table public.product_images enable row level security;
alter table public.product_documents enable row level security;
alter table public.product_certificates enable row level security;
alter table public.product_registration_fields enable row level security;
alter table public.product_registration_values enable row level security;

grant select on public.product_images to anon, authenticated;
grant select on public.product_documents to anon, authenticated;
grant select on public.product_certificates to anon, authenticated;
grant select on public.product_registration_values to anon, authenticated;

grant select, insert, update on public.product_images to authenticated;
grant select, insert, update on public.product_documents to authenticated;
grant select, insert, update on public.product_certificates to authenticated;
grant select, insert, update on public.product_registration_fields to authenticated;
grant select, insert, update on public.product_registration_values to authenticated;

create policy product_images_public_select
on public.product_images
for select
to anon, authenticated
using (
  deleted_at is null
  and approval_status = 'approved'
  and visibility = 'public'
  and exists (
    select 1
    from public.products
    where products.id = product_images.product_id
      and products.approval_status = 'approved'
      and products.publish_status = 'published'
      and products.is_active = true
      and products.deleted_at is null
  )
);

create policy product_images_supplier_owner_select
on public.product_images
for select
to authenticated
using (
  deleted_at is null
  and exists (
    select 1
    from public.products
    where products.id = product_images.product_id
      and products.supplier_id = public.current_supplier_id()
      and products.deleted_at is null
  )
);

create policy product_images_supplier_owner_insert
on public.product_images
for insert
to authenticated
with check (
  approval_status in ('draft', 'submitted', 'reviewing')
  and visibility in ('public', 'restricted')
  and exists (
    select 1
    from public.products
    where products.id = product_images.product_id
      and products.supplier_id = public.current_supplier_id()
      and products.deleted_at is null
  )
  and exists (
    select 1
    from public.files
    where files.id = product_images.file_id
      and files.owner_profile_id = auth.uid()
      and files.bucket = 'product-files'
      and files.is_active = true
      and files.deleted_at is null
  )
);

create policy product_images_supplier_owner_update
on public.product_images
for update
to authenticated
using (
  deleted_at is null
  and approval_status in ('draft', 'submitted', 'reviewing', 'rejected')
  and exists (
    select 1
    from public.products
    where products.id = product_images.product_id
      and products.supplier_id = public.current_supplier_id()
      and products.deleted_at is null
  )
)
with check (
  approval_status in ('draft', 'submitted', 'reviewing')
  and visibility in ('public', 'restricted')
  and exists (
    select 1
    from public.products
    where products.id = product_images.product_id
      and products.supplier_id = public.current_supplier_id()
      and products.deleted_at is null
  )
  and exists (
    select 1
    from public.files
    where files.id = product_images.file_id
      and files.owner_profile_id = auth.uid()
      and files.bucket = 'product-files'
      and files.is_active = true
      and files.deleted_at is null
  )
);

create policy product_images_admin_select
on public.product_images
for select
to authenticated
using (public.is_admin());

create policy product_images_admin_insert
on public.product_images
for insert
to authenticated
with check (public.is_admin());

create policy product_images_admin_update
on public.product_images
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy product_documents_public_select
on public.product_documents
for select
to anon, authenticated
using (
  deleted_at is null
  and approval_status = 'approved'
  and visibility = 'public'
  and exists (
    select 1
    from public.products
    where products.id = product_documents.product_id
      and products.approval_status = 'approved'
      and products.publish_status = 'published'
      and products.is_active = true
      and products.deleted_at is null
  )
);

create policy product_documents_supplier_owner_select
on public.product_documents
for select
to authenticated
using (
  deleted_at is null
  and exists (
    select 1
    from public.products
    where products.id = product_documents.product_id
      and products.supplier_id = public.current_supplier_id()
      and products.deleted_at is null
  )
);

create policy product_documents_supplier_owner_insert
on public.product_documents
for insert
to authenticated
with check (
  approval_status in ('draft', 'submitted', 'reviewing')
  and visibility in ('restricted', 'public')
  and exists (
    select 1
    from public.products
    where products.id = product_documents.product_id
      and products.supplier_id = public.current_supplier_id()
      and products.deleted_at is null
  )
  and exists (
    select 1
    from public.files
    where files.id = product_documents.file_id
      and files.owner_profile_id = auth.uid()
      and files.bucket = 'product-files'
      and files.is_active = true
      and files.deleted_at is null
  )
);

create policy product_documents_supplier_owner_update
on public.product_documents
for update
to authenticated
using (
  deleted_at is null
  and approval_status in ('draft', 'submitted', 'reviewing', 'rejected')
  and exists (
    select 1
    from public.products
    where products.id = product_documents.product_id
      and products.supplier_id = public.current_supplier_id()
      and products.deleted_at is null
  )
)
with check (
  approval_status in ('draft', 'submitted', 'reviewing')
  and visibility in ('restricted', 'public')
  and exists (
    select 1
    from public.products
    where products.id = product_documents.product_id
      and products.supplier_id = public.current_supplier_id()
      and products.deleted_at is null
  )
  and exists (
    select 1
    from public.files
    where files.id = product_documents.file_id
      and files.owner_profile_id = auth.uid()
      and files.bucket = 'product-files'
      and files.is_active = true
      and files.deleted_at is null
  )
);

create policy product_documents_admin_select
on public.product_documents
for select
to authenticated
using (public.is_admin());

create policy product_documents_admin_insert
on public.product_documents
for insert
to authenticated
with check (public.is_admin());

create policy product_documents_admin_update
on public.product_documents
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy product_certificates_public_select
on public.product_certificates
for select
to anon, authenticated
using (
  deleted_at is null
  and approval_status = 'approved'
  and verification_status = 'verified'
  and public_display in ('summary', 'visible')
  and exists (
    select 1
    from public.products
    where products.id = product_certificates.product_id
      and products.approval_status = 'approved'
      and products.publish_status = 'published'
      and products.is_active = true
      and products.deleted_at is null
  )
);

create policy product_certificates_supplier_owner_select
on public.product_certificates
for select
to authenticated
using (
  deleted_at is null
  and exists (
    select 1
    from public.products
    where products.id = product_certificates.product_id
      and products.supplier_id = public.current_supplier_id()
      and products.deleted_at is null
  )
);

create policy product_certificates_supplier_owner_insert
on public.product_certificates
for insert
to authenticated
with check (
  approval_status in ('draft', 'submitted', 'reviewing')
  and verification_status = 'pending'
  and verified_by is null
  and verified_at is null
  and exists (
    select 1
    from public.products
    where products.id = product_certificates.product_id
      and products.supplier_id = public.current_supplier_id()
      and products.deleted_at is null
  )
  and (
    file_id is null
    or exists (
      select 1
      from public.files
      where files.id = product_certificates.file_id
        and files.owner_profile_id = auth.uid()
        and files.bucket = 'product-files'
        and files.is_active = true
        and files.deleted_at is null
    )
  )
);

create policy product_certificates_supplier_owner_update
on public.product_certificates
for update
to authenticated
using (
  deleted_at is null
  and approval_status in ('draft', 'submitted', 'reviewing', 'rejected')
  and exists (
    select 1
    from public.products
    where products.id = product_certificates.product_id
      and products.supplier_id = public.current_supplier_id()
      and products.deleted_at is null
  )
)
with check (
  approval_status in ('draft', 'submitted', 'reviewing')
  and verification_status = 'pending'
  and verified_by is null
  and verified_at is null
  and exists (
    select 1
    from public.products
    where products.id = product_certificates.product_id
      and products.supplier_id = public.current_supplier_id()
      and products.deleted_at is null
  )
  and (
    file_id is null
    or exists (
      select 1
      from public.files
      where files.id = product_certificates.file_id
        and files.owner_profile_id = auth.uid()
        and files.bucket = 'product-files'
        and files.is_active = true
        and files.deleted_at is null
    )
  )
);

create policy product_certificates_admin_select
on public.product_certificates
for select
to authenticated
using (public.is_admin());

create policy product_certificates_admin_insert
on public.product_certificates
for insert
to authenticated
with check (public.is_admin());

create policy product_certificates_admin_update
on public.product_certificates
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy product_registration_fields_authenticated_select
on public.product_registration_fields
for select
to authenticated
using (
  is_active = true
  and deleted_at is null
);

create policy product_registration_fields_admin_select
on public.product_registration_fields
for select
to authenticated
using (public.is_admin());

create policy product_registration_fields_admin_insert
on public.product_registration_fields
for insert
to authenticated
with check (public.is_admin());

create policy product_registration_fields_admin_update
on public.product_registration_fields
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy product_registration_values_public_select
on public.product_registration_values
for select
to anon, authenticated
using (
  deleted_at is null
  and approval_status = 'approved'
  and public_display in ('summary', 'visible')
  and exists (
    select 1
    from public.products
    where products.id = product_registration_values.product_id
      and products.approval_status = 'approved'
      and products.publish_status = 'published'
      and products.is_active = true
      and products.deleted_at is null
  )
);

create policy product_registration_values_supplier_owner_select
on public.product_registration_values
for select
to authenticated
using (
  deleted_at is null
  and exists (
    select 1
    from public.products
    where products.id = product_registration_values.product_id
      and products.supplier_id = public.current_supplier_id()
      and products.deleted_at is null
  )
);

create policy product_registration_values_supplier_owner_insert
on public.product_registration_values
for insert
to authenticated
with check (
  approval_status in ('draft', 'submitted', 'reviewing')
  and exists (
    select 1
    from public.products
    where products.id = product_registration_values.product_id
      and products.supplier_id = public.current_supplier_id()
      and products.deleted_at is null
  )
);

create policy product_registration_values_supplier_owner_update
on public.product_registration_values
for update
to authenticated
using (
  deleted_at is null
  and approval_status in ('draft', 'submitted', 'reviewing', 'rejected')
  and exists (
    select 1
    from public.products
    where products.id = product_registration_values.product_id
      and products.supplier_id = public.current_supplier_id()
      and products.deleted_at is null
  )
)
with check (
  approval_status in ('draft', 'submitted', 'reviewing')
  and exists (
    select 1
    from public.products
    where products.id = product_registration_values.product_id
      and products.supplier_id = public.current_supplier_id()
      and products.deleted_at is null
  )
);

create policy product_registration_values_admin_select
on public.product_registration_values
for select
to authenticated
using (public.is_admin());

create policy product_registration_values_admin_insert
on public.product_registration_values
for insert
to authenticated
with check (public.is_admin());

create policy product_registration_values_admin_update
on public.product_registration_values
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

comment on policy product_images_public_select on public.product_images is
  'Public can read only approved public images for approved and published products.';
comment on policy product_documents_public_select on public.product_documents is
  'Public can read only approved public documents for approved and published products. File/Storage access remains separately governed.';
comment on policy product_certificates_public_select on public.product_certificates is
  'Public can read only approved verified certificate metadata for approved and published products.';
comment on policy product_registration_values_public_select on public.product_registration_values is
  'Public can read only approved visible/summary values for approved and published products.';

commit;
