-- Product registration core migration
-- Logical scope: 016_product_registration_core.sql
-- Generated by Supabase CLI as 20260701120539_product_registration_core.sql.
--
-- Purpose:
-- - Add product publish/review compatibility columns.
-- - Add product gallery, document, certificate, registration field, and
--   registration value tables.
--
-- Safety:
-- - Additive-only.
-- - No data mutation.
-- - No destructive schema changes.
-- - No public price columns.
-- - No Buyer PII columns.
-- - No Supplier-Buyer direct contact columns.
-- - No broad public/authenticated policies.
-- - RLS is enabled for new public tables, with policies deferred.

begin;

alter table public.products
  add column if not exists slug text,
  add column if not exists publish_status text not null default 'draft',
  add column if not exists published_at timestamptz,
  add column if not exists submitted_at timestamptz,
  add column if not exists reviewed_by uuid,
  add column if not exists reviewed_at timestamptz,
  add column if not exists review_note text;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'products_publish_status_check'
      and conrelid = 'public.products'::regclass
  ) then
    alter table public.products
      add constraint products_publish_status_check
      check (publish_status in ('draft', 'published', 'hidden', 'archived'))
      not valid;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'products_reviewed_by_fkey'
      and conrelid = 'public.products'::regclass
  ) then
    alter table public.products
      add constraint products_reviewed_by_fkey
      foreign key (reviewed_by)
      references public.profiles(id)
      on delete set null
      not valid;
  end if;
end $$;

create unique index if not exists products_slug_active_unique_idx
  on public.products(slug)
  where slug is not null and deleted_at is null;

create index if not exists products_publish_status_idx
  on public.products(publish_status);

create index if not exists products_submitted_at_idx
  on public.products(submitted_at);

create index if not exists products_reviewed_by_idx
  on public.products(reviewed_by);

create table if not exists public.product_images (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  file_id uuid not null references public.files(id) on delete restrict,
  image_role text not null default 'gallery',
  alt_text text,
  caption text,
  sort_order integer not null default 0,
  is_primary boolean not null default false,
  approval_status text not null default 'draft',
  visibility text not null default 'public',
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  deleted_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint product_images_role_check check (
    image_role in ('primary', 'gallery', 'application', 'technical', 'environment')
  ),
  constraint product_images_approval_status_check check (
    approval_status in ('draft', 'submitted', 'reviewing', 'approved', 'rejected', 'suspended')
  ),
  constraint product_images_visibility_check check (
    visibility in ('public', 'restricted', 'admin')
  ),
  constraint product_images_sort_order_check check (sort_order >= 0)
);

create table if not exists public.product_documents (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  file_id uuid not null references public.files(id) on delete restrict,
  document_type text not null,
  title text not null,
  description text,
  visibility text not null default 'restricted',
  approval_status text not null default 'draft',
  sort_order integer not null default 0,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  deleted_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint product_documents_type_check check (
    document_type in ('catalog', 'technical_sheet', 'test_report', 'certificate_file', 'manual', 'other')
  ),
  constraint product_documents_visibility_check check (
    visibility in ('public', 'restricted', 'admin')
  ),
  constraint product_documents_approval_status_check check (
    approval_status in ('draft', 'submitted', 'reviewing', 'approved', 'rejected', 'suspended')
  ),
  constraint product_documents_sort_order_check check (sort_order >= 0)
);

create table if not exists public.product_certificates (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  file_id uuid references public.files(id) on delete set null,
  certificate_type text not null,
  title text not null,
  issuer text,
  certificate_number text,
  issued_at date,
  expires_at date,
  verification_status text not null default 'pending',
  public_display text not null default 'summary',
  approval_status text not null default 'draft',
  verified_by uuid references public.profiles(id) on delete set null,
  verified_at timestamptz,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  deleted_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint product_certificates_type_check check (
    certificate_type in (
      'supplier_verification',
      'product_approval',
      'quality',
      'safety',
      'fda',
      'iso',
      'ce',
      'other'
    )
  ),
  constraint product_certificates_verification_status_check check (
    verification_status in ('pending', 'verified', 'rejected', 'expired')
  ),
  constraint product_certificates_public_display_check check (
    public_display in ('hidden', 'summary', 'visible')
  ),
  constraint product_certificates_approval_status_check check (
    approval_status in ('draft', 'submitted', 'reviewing', 'approved', 'rejected', 'suspended')
  )
);

create table if not exists public.product_registration_fields (
  id uuid primary key default gen_random_uuid(),
  field_key text not null,
  group_key text not null,
  label text not null,
  help_text text,
  input_type text not null,
  options jsonb not null default '[]'::jsonb,
  requirement text not null default 'optional',
  public_display text not null default 'hidden',
  category_id uuid references public.categories(id) on delete set null,
  industry_id uuid references public.industries(id) on delete set null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint product_registration_fields_input_type_check check (
    input_type in ('text', 'textarea', 'select', 'url', 'file', 'number', 'boolean')
  ),
  constraint product_registration_fields_options_check check (
    jsonb_typeof(options) = 'array'
  ),
  constraint product_registration_fields_requirement_check check (
    requirement in ('required', 'recommended', 'optional')
  ),
  constraint product_registration_fields_public_display_check check (
    public_display in ('hidden', 'summary', 'visible')
  ),
  constraint product_registration_fields_sort_order_check check (sort_order >= 0)
);

create table if not exists public.product_registration_values (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  field_id uuid references public.product_registration_fields(id) on delete set null,
  field_key text not null,
  group_key text not null,
  value_text text,
  value_json jsonb not null default '{}'::jsonb,
  public_display text not null default 'hidden',
  approval_status text not null default 'draft',
  sort_order integer not null default 0,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  deleted_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint product_registration_values_public_display_check check (
    public_display in ('hidden', 'summary', 'visible')
  ),
  constraint product_registration_values_approval_status_check check (
    approval_status in ('draft', 'submitted', 'reviewing', 'approved', 'rejected', 'suspended')
  ),
  constraint product_registration_values_sort_order_check check (sort_order >= 0)
);

create index if not exists product_images_product_id_idx
  on public.product_images(product_id);
create index if not exists product_images_file_id_idx
  on public.product_images(file_id);
create index if not exists product_images_visibility_idx
  on public.product_images(visibility);
create index if not exists product_images_approval_status_idx
  on public.product_images(approval_status);
create index if not exists product_images_sort_order_idx
  on public.product_images(product_id, sort_order);
create unique index if not exists product_images_primary_active_idx
  on public.product_images(product_id)
  where is_primary = true and deleted_at is null;

create index if not exists product_documents_product_id_idx
  on public.product_documents(product_id);
create index if not exists product_documents_file_id_idx
  on public.product_documents(file_id);
create index if not exists product_documents_type_idx
  on public.product_documents(document_type);
create index if not exists product_documents_visibility_idx
  on public.product_documents(visibility);
create index if not exists product_documents_approval_status_idx
  on public.product_documents(approval_status);
create index if not exists product_documents_sort_order_idx
  on public.product_documents(product_id, sort_order);

create index if not exists product_certificates_product_id_idx
  on public.product_certificates(product_id);
create index if not exists product_certificates_file_id_idx
  on public.product_certificates(file_id);
create index if not exists product_certificates_type_idx
  on public.product_certificates(certificate_type);
create index if not exists product_certificates_verification_status_idx
  on public.product_certificates(verification_status);
create index if not exists product_certificates_public_display_idx
  on public.product_certificates(public_display);
create index if not exists product_certificates_approval_status_idx
  on public.product_certificates(approval_status);

create index if not exists product_registration_fields_field_key_idx
  on public.product_registration_fields(field_key);
create index if not exists product_registration_fields_group_key_idx
  on public.product_registration_fields(group_key);
create index if not exists product_registration_fields_category_id_idx
  on public.product_registration_fields(category_id);
create index if not exists product_registration_fields_industry_id_idx
  on public.product_registration_fields(industry_id);
create index if not exists product_registration_fields_active_idx
  on public.product_registration_fields(is_active);
create index if not exists product_registration_fields_sort_order_idx
  on public.product_registration_fields(group_key, sort_order);
create unique index if not exists product_registration_fields_global_key_idx
  on public.product_registration_fields(field_key)
  where category_id is null and industry_id is null and deleted_at is null;

create index if not exists product_registration_values_product_id_idx
  on public.product_registration_values(product_id);
create index if not exists product_registration_values_field_id_idx
  on public.product_registration_values(field_id);
create index if not exists product_registration_values_field_key_idx
  on public.product_registration_values(field_key);
create index if not exists product_registration_values_public_display_idx
  on public.product_registration_values(public_display);
create index if not exists product_registration_values_approval_status_idx
  on public.product_registration_values(approval_status);
create index if not exists product_registration_values_sort_order_idx
  on public.product_registration_values(product_id, sort_order);
create unique index if not exists product_registration_values_active_field_idx
  on public.product_registration_values(product_id, field_key)
  where deleted_at is null;

alter table public.product_images enable row level security;
alter table public.product_documents enable row level security;
alter table public.product_certificates enable row level security;
alter table public.product_registration_fields enable row level security;
alter table public.product_registration_values enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_trigger where tgname = 'product_images_set_updated_at'
  ) then
    execute 'create trigger product_images_set_updated_at before update on public.product_images for each row execute function public.set_updated_at()';
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_trigger where tgname = 'product_documents_set_updated_at'
  ) then
    execute 'create trigger product_documents_set_updated_at before update on public.product_documents for each row execute function public.set_updated_at()';
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_trigger where tgname = 'product_certificates_set_updated_at'
  ) then
    execute 'create trigger product_certificates_set_updated_at before update on public.product_certificates for each row execute function public.set_updated_at()';
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_trigger where tgname = 'product_registration_fields_set_updated_at'
  ) then
    execute 'create trigger product_registration_fields_set_updated_at before update on public.product_registration_fields for each row execute function public.set_updated_at()';
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_trigger where tgname = 'product_registration_values_set_updated_at'
  ) then
    execute 'create trigger product_registration_values_set_updated_at before update on public.product_registration_values for each row execute function public.set_updated_at()';
  end if;
end $$;

comment on column public.products.slug is
  'Public product route candidate. Backfill and publish rules must be reviewed before app queries depend on it.';
comment on column public.products.publish_status is
  'Product publish lifecycle independent from approval_status. Existing rows default to draft until explicit publish backfill is approved.';
comment on column public.products.review_note is
  'Admin review note for product workflow. Do not expose on public product pages.';

comment on table public.product_images is
  'Product image gallery relation. Public access requires approved parent product, approved image, RLS policy, and file visibility checks.';
comment on table public.product_documents is
  'Product document/catalog relation. Documents default restricted and must not become public without Admin approval and RLS.';
comment on table public.product_certificates is
  'Product certificate metadata for public-safe certificate cards and Admin verification review.';
comment on table public.product_registration_fields is
  'Admin-configurable product registration field definitions. Default seed data is intentionally deferred.';
comment on table public.product_registration_values is
  'Supplier-entered product registration values. Public display is controlled per field/value and must not include price or Buyer PII.';

comment on column public.product_documents.visibility is
  'Use restricted by default. Public documents require approval and matching Storage/file visibility.';
comment on column public.product_certificates.public_display is
  'Controls whether certificate metadata is hidden, summary-only, or visible. Certificate files remain separately governed.';
comment on column public.product_registration_values.public_display is
  'Controls product detail projection. Hidden values must not be returned on public product pages.';

commit;
