import type { LandingCountryServiceConfig } from "@/components/public/landing/landing-country-service-section";
import type { LandingFeaturedMarketplaceConfig } from "@/components/public/landing/landing-featured-marketplace-section";
import type { LandingHeroConfig } from "@/components/public/landing/landing-hero-section";
import type { LandingNoticeCtaFooterConfig } from "@/components/public/landing/landing-notice-cta-footer-section";
import type { LandingRoleGatewayConfig } from "@/components/public/landing/landing-role-gateway-section";
import { t } from "@/lib/i18n/translation";

const visiblePublishedState = {
  publishState: "published" as const,
  visibility: {
    endsAt: null,
    isVisible: true,
    startsAt: null,
  },
};

const hero: LandingHeroConfig = {
  ...visiblePublishedState,
  eyebrow: t("home.hero.builderEyebrow"),
  featuredKeywords: [
    { label: "K-Beauty" },
    { label: "Food Supplement" },
    { label: "Industrial" },
    { label: "EPC" },
    { label: "Thailand FDA" },
  ],
  kpiItems: [
    {
      label: t("home.hero.kpi.roles.label"),
      value: t("home.hero.kpi.roles.value"),
    },
    {
      label: t("home.hero.kpi.brokerage.label"),
      value: t("home.hero.kpi.brokerage.value"),
    },
    {
      label: t("home.hero.kpi.privacy.label"),
      value: t("home.hero.kpi.privacy.value"),
    },
  ],
  primaryCta: {
    href: "/signup/supplier",
    label: t("home.hero.cta.supplier"),
  },
  roleCtas: [
    {
      href: "/signup/supplier",
      label: t("home.hero.role.supplier"),
    },
    {
      href: "/signup/buyer",
      label: t("home.hero.role.buyer"),
    },
    {
      href: "/signup/agent",
      label: t("home.hero.role.agent"),
    },
    {
      href: "/signup/professor",
      label: t("home.hero.role.professor"),
    },
    {
      href: "/signup/student",
      label: t("home.hero.role.student"),
    },
  ],
  searchPlaceholder: t("home.hero.searchPlaceholder"),
  secondaryCta: {
    href: "/login",
    label: t("nav.signIn"),
  },
  subtitle: t("home.hero.builderSubtitle"),
  title: t("home.hero.builderTitle"),
  trustItems: [
    { label: t("home.hero.trust.adminApproval") },
    { label: t("home.hero.trust.brokerage") },
    { label: t("home.hero.trust.pii") },
  ],
  visualTiles: [
    {
      imageAlt: "Korean cosmetic product preview",
      imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=900&q=80",
      label: t("home.hero.tile.beauty"),
    },
    {
      imageAlt: "Korean industrial supply preview",
      imageUrl: "https://images.unsplash.com/photo-1513828583688-c52646db42da?auto=format&fit=crop&w=900&q=80",
      label: t("home.hero.tile.industrial"),
    },
    {
      imageAlt: "Global buyer meeting preview",
      imageUrl: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=900&q=80",
      label: t("home.hero.tile.matching"),
    },
  ],
};

const roleGateway: LandingRoleGatewayConfig = {
  ...visiblePublishedState,
  eyebrow: t("home.roleGateway.eyebrow"),
  roles: [
    {
      description: t("home.roleGateway.supplier.description"),
      primaryCtaHref: "/signup/supplier",
      primaryCtaLabel: t("home.roleGateway.supplier.cta"),
      roleKey: "supplier",
      secondaryText: t("home.roleGateway.supplier.secondary"),
      statusLabel: t("home.roleGateway.supplier.status"),
      title: t("home.roleGateway.supplier.title"),
    },
    {
      description: t("home.roleGateway.buyer.description"),
      primaryCtaHref: "/signup/buyer",
      primaryCtaLabel: t("home.roleGateway.buyer.cta"),
      roleKey: "buyer",
      secondaryText: t("home.roleGateway.buyer.secondary"),
      statusLabel: t("home.roleGateway.buyer.status"),
      title: t("home.roleGateway.buyer.title"),
    },
    {
      description: t("home.roleGateway.agent.description"),
      primaryCtaHref: "/signup/agent",
      primaryCtaLabel: t("home.roleGateway.agent.cta"),
      roleKey: "agent",
      secondaryText: t("home.roleGateway.agent.secondary"),
      statusLabel: t("home.roleGateway.agent.status"),
      title: t("home.roleGateway.agent.title"),
    },
    {
      description: t("home.roleGateway.professor.description"),
      primaryCtaHref: "/signup/professor",
      primaryCtaLabel: t("home.roleGateway.professor.cta"),
      roleKey: "professor",
      secondaryText: t("home.roleGateway.professor.secondary"),
      statusLabel: t("home.roleGateway.professor.status"),
      title: t("home.roleGateway.professor.title"),
    },
    {
      description: t("home.roleGateway.student.description"),
      primaryCtaHref: "/signup/student",
      primaryCtaLabel: t("home.roleGateway.student.cta"),
      roleKey: "student",
      secondaryText: t("home.roleGateway.student.secondary"),
      statusLabel: t("home.roleGateway.student.status"),
      title: t("home.roleGateway.student.title"),
    },
  ],
  sectionId: "landing-role-gateway",
  subtitle: t("home.roleGateway.subtitle"),
  title: t("home.roleGateway.title"),
};

const featuredMarketplace: LandingFeaturedMarketplaceConfig = {
  ...visiblePublishedState,
  eyebrow: t("home.featuredMarketplace.eyebrow"),
  groups: [
    {
      description: t("home.featuredMarketplace.suppliers.description"),
      groupKey: "featured_suppliers",
      isListEnabled: false,
      items: [
        {
          badge: t("home.featuredMarketplace.suppliers.item1.badge"),
          ctaLabel: t("home.featuredMarketplace.supplierCta"),
          description: t("home.featuredMarketplace.suppliers.item1.description"),
          href: "/commercial",
          id: "featured-supplier-k-beauty-export-desk",
          meta: t("home.featuredMarketplace.suppliers.item1.meta"),
          title: t("home.featuredMarketplace.suppliers.item1.title"),
          type: "supplier",
        },
        {
          badge: t("home.featuredMarketplace.suppliers.item2.badge"),
          ctaLabel: t("home.featuredMarketplace.supplierCta"),
          description: t("home.featuredMarketplace.suppliers.item2.description"),
          href: "/industrial",
          id: "featured-supplier-industrial-parts-network",
          meta: t("home.featuredMarketplace.suppliers.item2.meta"),
          title: t("home.featuredMarketplace.suppliers.item2.title"),
          type: "supplier",
        },
        {
          badge: t("home.featuredMarketplace.suppliers.item3.badge"),
          ctaLabel: t("home.featuredMarketplace.supplierCta"),
          description: t("home.featuredMarketplace.suppliers.item3.description"),
          href: "/thailand-fda-service",
          id: "featured-supplier-food-supplement-partner",
          meta: t("home.featuredMarketplace.suppliers.item3.meta"),
          title: t("home.featuredMarketplace.suppliers.item3.title"),
          type: "supplier",
        },
      ],
      listCtaLabel: t("home.featuredMarketplace.listComingSoon"),
      listHref: "/suppliers",
      title: t("home.featuredMarketplace.suppliers.title"),
    },
    {
      description: t("home.featuredMarketplace.products.description"),
      groupKey: "featured_products",
      isListEnabled: false,
      items: [
        {
          badge: t("home.featuredMarketplace.products.item1.badge"),
          ctaLabel: t("home.featuredMarketplace.productCta"),
          description: t("home.featuredMarketplace.products.item1.description"),
          href: "/commercial",
          id: "featured-product-skincare-starter-set",
          meta: t("home.featuredMarketplace.products.item1.meta"),
          title: t("home.featuredMarketplace.products.item1.title"),
          type: "product",
        },
        {
          badge: t("home.featuredMarketplace.products.item2.badge"),
          ctaLabel: t("home.featuredMarketplace.productCta"),
          description: t("home.featuredMarketplace.products.item2.description"),
          href: "/industrial",
          id: "featured-product-factory-automation-module",
          meta: t("home.featuredMarketplace.products.item2.meta"),
          title: t("home.featuredMarketplace.products.item2.title"),
          type: "product",
        },
        {
          badge: t("home.featuredMarketplace.products.item3.badge"),
          ctaLabel: t("home.featuredMarketplace.productCta"),
          description: t("home.featuredMarketplace.products.item3.description"),
          href: "/thailand-fda-service",
          id: "featured-product-supplement-label-ready-package",
          meta: t("home.featuredMarketplace.products.item3.meta"),
          title: t("home.featuredMarketplace.products.item3.title"),
          type: "product",
        },
      ],
      listCtaLabel: t("home.featuredMarketplace.listComingSoon"),
      listHref: "/products",
      title: t("home.featuredMarketplace.products.title"),
    },
    {
      description: t("home.featuredMarketplace.buyRequests.description"),
      groupKey: "buy_requests",
      isListEnabled: false,
      items: [
        {
          badge: t("home.featuredMarketplace.buyRequests.item1.badge"),
          ctaLabel: t("home.featuredMarketplace.buyRequestCta"),
          description: t("home.featuredMarketplace.buyRequests.item1.description"),
          href: "/buy-sell/buy-requests",
          id: "featured-buy-request-thailand-retail-sourcing-brief",
          meta: t("home.featuredMarketplace.buyRequests.item1.meta"),
          title: t("home.featuredMarketplace.buyRequests.item1.title"),
          type: "buy_request",
        },
        {
          badge: t("home.featuredMarketplace.buyRequests.item2.badge"),
          ctaLabel: t("home.featuredMarketplace.buyRequestCta"),
          description: t("home.featuredMarketplace.buyRequests.item2.description"),
          href: "/buy-sell/buy-requests",
          id: "featured-buy-request-vietnam-machinery-inquiry",
          meta: t("home.featuredMarketplace.buyRequests.item2.meta"),
          title: t("home.featuredMarketplace.buyRequests.item2.title"),
          type: "buy_request",
        },
        {
          badge: t("home.featuredMarketplace.buyRequests.item3.badge"),
          ctaLabel: t("home.featuredMarketplace.buyRequestCta"),
          description: t("home.featuredMarketplace.buyRequests.item3.description"),
          href: "/buy-sell/buy-requests",
          id: "featured-buy-request-uae-project-supply-request",
          meta: t("home.featuredMarketplace.buyRequests.item3.meta"),
          title: t("home.featuredMarketplace.buyRequests.item3.title"),
          type: "buy_request",
        },
      ],
      listCtaLabel: t("home.featuredMarketplace.listComingSoon"),
      listHref: "/buy-requests",
      title: t("home.featuredMarketplace.buyRequests.title"),
    },
  ],
  policyNotes: [
    t("home.featuredMarketplace.policy.buyerContact"),
    t("home.featuredMarketplace.policy.directContact"),
    t("home.featuredMarketplace.policy.brokerage"),
  ],
  sectionId: "landing-featured-marketplace",
  subtitle: t("home.featuredMarketplace.subtitle"),
  title: t("home.featuredMarketplace.title"),
};

const countryService: LandingCountryServiceConfig = {
  ...visiblePublishedState,
  countryGatewaySubtitle: t("home.countryService.country.subtitle"),
  countryGatewayTitle: t("home.countryService.country.title"),
  countryGateways: [
    {
      countryName: t("home.countryService.country.korea.name"),
      ctaLabel: t("home.countryService.viewGateway"),
      description: t("home.countryService.country.korea.description"),
      href: "/commercial",
      id: "country-gateway-korea",
      marketLabel: t("home.countryService.country.korea.market"),
      statusLabel: t("home.countryService.country.korea.status"),
    },
    {
      countryName: t("home.countryService.country.thailand.name"),
      ctaLabel: t("home.countryService.viewGateway"),
      description: t("home.countryService.country.thailand.description"),
      href: "/thailand-fda-service",
      id: "country-gateway-thailand",
      marketLabel: t("home.countryService.country.thailand.market"),
      statusLabel: t("home.countryService.country.thailand.status"),
    },
    {
      countryName: t("home.countryService.country.japan.name"),
      ctaLabel: t("home.countryService.comingSoon"),
      description: t("home.countryService.country.japan.description"),
      href: "/countries/japan",
      id: "country-gateway-japan",
      isEnabled: false,
      marketLabel: t("home.countryService.country.japan.market"),
      statusLabel: t("home.countryService.country.japan.status"),
    },
    {
      countryName: t("home.countryService.country.vietnam.name"),
      ctaLabel: t("home.countryService.comingSoon"),
      description: t("home.countryService.country.vietnam.description"),
      href: "/countries/vietnam",
      id: "country-gateway-vietnam",
      isEnabled: false,
      marketLabel: t("home.countryService.country.vietnam.market"),
      statusLabel: t("home.countryService.country.vietnam.status"),
    },
    {
      countryName: t("home.countryService.country.indonesia.name"),
      ctaLabel: t("home.countryService.comingSoon"),
      description: t("home.countryService.country.indonesia.description"),
      href: "/countries/indonesia",
      id: "country-gateway-indonesia",
      isEnabled: false,
      marketLabel: t("home.countryService.country.indonesia.market"),
      statusLabel: t("home.countryService.country.indonesia.status"),
    },
  ],
  eyebrow: t("home.countryService.eyebrow"),
  sectionId: "landing-country-service-gateway",
  serviceGatewaySubtitle: t("home.countryService.service.subtitle"),
  serviceGatewayTitle: t("home.countryService.service.title"),
  serviceGateways: [
    {
      ctaLabel: t("home.countryService.viewGateway"),
      description: t("home.countryService.service.fda.description"),
      href: "/thailand-fda-service",
      id: "service-gateway-thailand-fda",
      serviceName: t("home.countryService.service.fda.name"),
      statusLabel: t("home.countryService.service.fda.status"),
    },
    {
      ctaLabel: t("home.countryService.viewGateway"),
      description: t("home.countryService.service.events.description"),
      href: "/events",
      id: "service-gateway-events",
      serviceName: t("home.countryService.service.events.name"),
      statusLabel: t("home.countryService.service.events.status"),
    },
    {
      ctaLabel: t("home.countryService.comingSoon"),
      description: t("home.countryService.service.studentShowcase.description"),
      href: "/student-showcase",
      id: "service-gateway-student-showcase",
      isEnabled: false,
      serviceName: t("home.countryService.service.studentShowcase.name"),
      statusLabel: t("home.countryService.service.studentShowcase.status"),
    },
    {
      ctaLabel: t("home.countryService.viewGateway"),
      description: t("home.countryService.service.buyRequestBrokerage.description"),
      href: "/buy-sell/buy-requests",
      id: "service-gateway-buy-request-brokerage",
      serviceName: t("home.countryService.service.buyRequestBrokerage.name"),
      statusLabel: t("home.countryService.service.buyRequestBrokerage.status"),
    },
    {
      ctaLabel: t("home.countryService.comingSoon"),
      description: t("home.countryService.service.supplierMembership.description"),
      href: "/supplier-membership",
      id: "service-gateway-supplier-membership",
      isEnabled: false,
      serviceName: t("home.countryService.service.supplierMembership.name"),
      statusLabel: t("home.countryService.service.supplierMembership.status"),
    },
  ],
  subtitle: t("home.countryService.subtitle"),
  title: t("home.countryService.title"),
};

const noticeCtaFooter: LandingNoticeCtaFooterConfig = {
  ...visiblePublishedState,
  brandLabel: t("brand.name"),
  eventItems: [
    {
      dateLabel: t("home.noticeCtaFooter.events.item1.date"),
      description: t("home.noticeCtaFooter.events.item1.description"),
      href: "/events",
      id: "footer-event-buyer-mission",
      locationLabel: t("home.noticeCtaFooter.events.item1.location"),
      statusLabel: t("home.noticeCtaFooter.events.item1.status"),
      title: t("home.noticeCtaFooter.events.item1.title"),
    },
    {
      dateLabel: t("home.noticeCtaFooter.events.item2.date"),
      description: t("home.noticeCtaFooter.events.item2.description"),
      href: "/events",
      id: "footer-event-regulatory-webinar",
      locationLabel: t("home.noticeCtaFooter.events.item2.location"),
      statusLabel: t("home.noticeCtaFooter.events.item2.status"),
      title: t("home.noticeCtaFooter.events.item2.title"),
    },
    {
      dateLabel: t("home.noticeCtaFooter.events.item3.date"),
      description: t("home.noticeCtaFooter.events.item3.description"),
      href: "/events",
      id: "footer-event-supplier-session",
      locationLabel: t("home.noticeCtaFooter.events.item3.location"),
      statusLabel: t("home.noticeCtaFooter.events.item3.status"),
      title: t("home.noticeCtaFooter.events.item3.title"),
    },
  ],
  eventTitle: t("home.noticeCtaFooter.events.title"),
  eyebrow: t("home.noticeCtaFooter.eyebrow"),
  finalCta: {
    primaryCta: {
      href: "/signup/supplier",
      label: t("home.noticeCtaFooter.finalCta.primary"),
    },
    secondaryCta: {
      href: "/signup/buyer",
      label: t("home.noticeCtaFooter.finalCta.secondary"),
    },
    signInCta: {
      href: "/login",
      label: t("nav.signIn"),
    },
    subtitle: t("home.noticeCtaFooter.finalCta.subtitle"),
    title: t("home.noticeCtaFooter.finalCta.title"),
  },
  footerGroups: [
    {
      groupTitle: t("home.noticeCtaFooter.footer.platform"),
      links: [
        { href: "/commercial", label: t("nav.commercial") },
        { href: "/industrial", label: t("nav.industrial") },
        { href: "/epc", label: t("nav.epc") },
        { href: "/buy-sell", label: t("nav.buySell") },
      ],
    },
    {
      groupTitle: t("home.noticeCtaFooter.footer.services"),
      links: [
        { href: "/thailand-fda-service", label: t("home.countryService.service.fda.name") },
        { href: "/events", label: t("nav.events") },
        { href: "/buy-sell/buy-requests", label: t("home.countryService.service.buyRequestBrokerage.name") },
        {
          href: "/supplier-membership",
          isEnabled: false,
          label: t("home.countryService.service.supplierMembership.name"),
        },
      ],
    },
    {
      groupTitle: t("home.noticeCtaFooter.footer.roles"),
      links: [
        { href: "/signup/supplier", label: t("home.roleGateway.supplier.title") },
        { href: "/signup/buyer", label: t("home.roleGateway.buyer.title") },
        { href: "/signup/agent", label: t("home.roleGateway.agent.title") },
        { href: "/signup/professor", label: t("home.roleGateway.professor.title") },
        { href: "/signup/student", label: t("home.roleGateway.student.title") },
      ],
    },
    {
      groupTitle: t("home.noticeCtaFooter.footer.legalSupport"),
      links: [
        { href: "/privacy", label: t("legal.privacy.title") },
        { href: "/terms", label: t("legal.terms.title") },
        { href: "/cookies", label: t("legal.cookies.title") },
        { href: "/guide", label: t("legal.guide.title") },
        {
          href: "/support",
          isEnabled: false,
          label: t("home.noticeCtaFooter.footer.supportComingSoon"),
        },
      ],
    },
  ],
  footerTagline: t("footer.tagline"),
  noticeItems: [
    {
      dateLabel: t("home.noticeCtaFooter.notice.item1.date"),
      description: t("home.noticeCtaFooter.notice.item1.description"),
      href: "/notice",
      id: "footer-notice-approval-first",
      statusLabel: t("home.noticeCtaFooter.notice.item1.status"),
      title: t("home.noticeCtaFooter.notice.item1.title"),
    },
    {
      dateLabel: t("home.noticeCtaFooter.notice.item2.date"),
      description: t("home.noticeCtaFooter.notice.item2.description"),
      href: "/notice",
      id: "footer-notice-brokerage-policy",
      statusLabel: t("home.noticeCtaFooter.notice.item2.status"),
      title: t("home.noticeCtaFooter.notice.item2.title"),
    },
    {
      dateLabel: t("home.noticeCtaFooter.notice.item3.date"),
      description: t("home.noticeCtaFooter.notice.item3.description"),
      href: "/notice",
      id: "footer-notice-builder-preview",
      statusLabel: t("home.noticeCtaFooter.notice.item3.status"),
      title: t("home.noticeCtaFooter.notice.item3.title"),
    },
  ],
  noticeTitle: t("home.noticeCtaFooter.notice.title"),
  rightsLabel: t("home.noticeCtaFooter.footer.rights"),
  sectionId: "landing-notice-cta-footer",
  subtitle: t("home.noticeCtaFooter.subtitle"),
  title: t("home.noticeCtaFooter.title"),
};

export const staticLandingConfig = {
  countryService,
  featuredMarketplace,
  hero,
  noticeCtaFooter,
  roleGateway,
};
